# TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY
#  TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY
# TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY
#  TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY

# TEST THE FULL GUI APPLICATION RUN BY PDYM:

pydm --hide-nav-bar --hide-status-bar --hide-menu-bar \
    -m "configDB_Prefix=${EPICS_IOC_TOP}/MpsConfiguration/MpsConfiguration-R2-207/database, \
    logicDB_Prefix=${EPICS_IOC_TOP}/MpsConfiguration/MpsConfiguration-R2-207/algorithm, \
    IOC_PREFIX=IOC:BSY0:MP01, \
    JSONFILEPATH=recent_states.json,\
    CUD = 'Summary',\
    accel_type = LCLS" \
    mps_gui_main.py