# TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY
#  TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY
# TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY
#  TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY TEMPORARY
 pydm --hide-nav-bar --hide-status-bar --hide-menu-bar \
    -m "configDB_Prefix=${EPICS_IOC_TOP}/MpsConfiguration-FACET/MpsConfiguration-FACET-R1-17/database/, \
    logicDB_Prefix=${EPICS_IOC_TOP}/MpsConfiguration-FACET/MpsConfiguration-FACET-R1-17/algorithm/, \
    IOC_PREFIX=IOC:SYS1:MP01, \
    JSONFILEPATH=recent_states_facet.json,\
    CUD = 'Summary',\
    accel_type = FACET" \
    mps_gui_main.py